// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhAxLCkhGrzQ8NvaROTsvDGc3pdEFhT9A',
    appId: '1:920186495722:web:4a99b6465672d4ec842d93',
    messagingSenderId: '920186495722',
    projectId: 'sat-math-22cc7',
    authDomain: 'sat-math-22cc7.firebaseapp.com',
    storageBucket: 'sat-math-22cc7.firebasestorage.app',
    measurementId: 'G-TDHZBT9M6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfHvNOWpbDCxRpfaajnLcqHFlvaKcYIEU',
    appId: '1:920186495722:android:1db9a55b381e2c3f842d93',
    messagingSenderId: '920186495722',
    projectId: 'sat-math-22cc7',
    storageBucket: 'sat-math-22cc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhtsoEieK9aMnM_QkPu7scB90UiFX8VLI',
    appId: '1:920186495722:ios:496cc4e69aefa9e2842d93',
    messagingSenderId: '920186495722',
    projectId: 'sat-math-22cc7',
    storageBucket: 'sat-math-22cc7.firebasestorage.app',
    iosBundleId: 'com.example.satMath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhtsoEieK9aMnM_QkPu7scB90UiFX8VLI',
    appId: '1:920186495722:ios:496cc4e69aefa9e2842d93',
    messagingSenderId: '920186495722',
    projectId: 'sat-math-22cc7',
    storageBucket: 'sat-math-22cc7.firebasestorage.app',
    iosBundleId: 'com.example.satMath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhAxLCkhGrzQ8NvaROTsvDGc3pdEFhT9A',
    appId: '1:920186495722:web:a2a60ded99592d3a842d93',
    messagingSenderId: '920186495722',
    projectId: 'sat-math-22cc7',
    authDomain: 'sat-math-22cc7.firebaseapp.com',
    storageBucket: 'sat-math-22cc7.firebasestorage.app',
    measurementId: 'G-9WV2QHBQYY',
  );
}
